### ISSUE TITLE
PEP should list all cases where forward refs still need quotes

### ISSUE THREAD

**Issue by gvanrossum** [ambv/static-annotations#6]
There are a few places where this PEP doesn't help in eliminating the need for quoting of forward refs. The PEP should list all such situations. Potential examples include:

- Type aliases
- Type variable bounds
- Instantiating generic classes in a base class
- I'm not sure this list is complete!

Examples of each:

- Type aliases. While the following example *could* be written by moving the type alias 'A' below the classes it references, the code is clearer if the definition of 'A' precedes its first use.

```py
A = Union['C', 'D']
class C:
    def method1(self, arg: A): ....
class D:
    def method2(self, arg: A): ...
```

- Type variable bounds. Needed for e.g. self-types, and again more readable with the type variable definition first (plus, mypy needs that order):

```py
T = TypeVar('T', bound='C')
class C:
    def copy(self: T) -> T: ...
```

- Instantiating generic classes in a base class. In the following example, presumably there's a human reason we want C defined before defining X and Y:

```py
class C(Tuple[X, Y]): ...
class X: ...
class Y: ...
```

**Comment by gvanrossum** [comment]
There are a few more, e.g. `NewType`.

**Comment by ambv** [comment]
The reason I didn't touch on this at all is that none of those cases are *annotations*. Yes, there's going to be stringified forward references if you're making calls, building type aliases, or using types as base classes.

You're right that it's probably worthwhile to mention it anyway.

**Comment by gvanrossum** [comment]
Please do.

**Comment by ambv** [comment]
Solved by ce3779135c06ccacf6634dff4478185c6b44d7d8. Leaving issue open pending discussion.

**Comment by ambv** [comment]
In general, @gvanrossum, I think I'm missing your **goal** with this list.

I focused on syntactic constructs that still require string literals, whereas your suggestion is to focus on an exhaustive list of all *typing constructs* that still require string literals. I can do that but I don't quite get why we need a list like this. As I said above, since this PEP is focusing on the syntactic construct of annotations, it obviously doesn't address any other issues with forward refs. Those would require a multi-pass compiler and that's AFAICT fundamentally incompatible with Python's top-down module instantiation. So, from my perspective, I'm mentioning the forward refs issue merely as courtesy to the reader who might otherwise hope for too much from this PEP.

But I'm clearly missing something. What's the goal of an exhaustive list of typing constructs that still require string literals to handle forward refs?

**Comment by gvanrossum** [comment]
Let's see. Your PEP is clearly motivated exclusively by typing (nobody who's using annotations for non-typing purposes asked for this). Because it affects the long-term semantics of annotations your PEP needs to exhaustively list backwards incompatibilities.

But I think it is also fair to warn people who are using types that your PEP doesn't address *all* issues with forward references, so people won't be surprised when they still have to explicitly add string quotes to types in some contexts.  For these it is not necessary to be exhaustive, but I think it is good to cover the bases. There seem to be two issues here: forward references and types that are only defined/imported inside `if TYPE_CHECKING`. And then there are a few broad categories where such types can appear outside annotations; it would be good to show examples of the common use cases here, e.g. TypeVar, type aliases, NewType and friends (e.g. TypedDict, NamedTuple), and cast(). I'd say that Union just falls under type aliases here.

**Comment by ambv** [comment]
Reworded in 3d237623b3cef96e59f067f3195581b8259108be.

**Comment by gvanrossum** [comment]
LGTM!
